package Presentacion;

import BO_Layer.BussinesObjects.OEmpleados;
import BO_Layer.Objects.BO_Empleados;
import BO_Layer.Objects.BO_Tabla;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author casol
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    
    private BO_Empleados BO_empleado = new BO_Empleados();
    private ArrayList<OEmpleados> Empleados;
            
    public Test() throws Exception 
    {
        initComponents();
        this.obtenerEmpleados();
        Cargar_Tabla(jt_EmpleadosBefore);
    }
    
    private void obtenerEmpleados() throws Exception{
        try{           
            Empleados = BO_empleado.Obtener_Empleados();
        }catch(Exception ex){
            throw ex;
        }
    }
    
    private void Cargar_Tabla(JTable pTablaEmpleados )
    {
        try
        {   
            DefaultTableModel modelotabla;

            Object columnas[] = {"id","Apellido","Nombre","Tipo de empleado", "Sueldo"};
            
            modelotabla = new DefaultTableModel(columnas,0);
            //dg_Grupo_familiar.Rows.Clear();
            
            pTablaEmpleados.setModel(modelotabla);
                                             
            for(int i=0;i<Empleados.size();i++){
                modelotabla.addRow(new Object[] {Empleados.get(i).getId_empleado(),Empleados.get(i).getApellido(), Empleados.get(i).getNombre(), Empleados.get(i).getTipo_de_empleado(), Empleados.get(i).getSueldo()} );
                System.out.println(Empleados.get(i).getApellido());
            }
        }
        catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ ex.getMessage()); ;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_EmpleadosBefore = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_EmpleadosAfter = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jt_EmpleadosBefore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jt_EmpleadosBefore);

        jButton1.setText("Incrementar sueldo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jt_EmpleadosAfter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jt_EmpleadosAfter);

        jButton2.setText("Guardar Cambios");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        try{
            BO_empleado.incrementarSueldo(Empleados);
            this.Cargar_Tabla(jt_EmpleadosAfter);
            JOptionPane.showMessageDialog(this, "Sueldo Incrementado Con Éxito"); //Mensaje de que salio todo piola
        }catch (Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Error "+ ex.getMessage()); ;
        }
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Iterar sobre los empleados mostrados en la tabla jt_EmpleadosAfter
    DefaultTableModel model = (DefaultTableModel) jt_EmpleadosAfter.getModel();
    for (int i = 0; i < model.getRowCount(); i++) {
        int idEmpleado = (int) model.getValueAt(i, 0); // 0 porque el Id esta en la 1era posicion (Columna nro1)
        float nuevoSueldo = (float) model.getValueAt(i, 4); // 4 porque el Sueldo esta en la 5ta posicion (Columna nro5)
        
        // Buscar al empleado en la lista de empleados
        for (OEmpleados empleado : Empleados) {
            if (empleado.getId_empleado() == idEmpleado) {
                empleado.setSueldo(nuevoSueldo); // Actualiza el sueldo de la lista
                try {
                    BO_empleado.Actualizar_Sueldo(empleado); // Guarda en la base de datos los cambios realizados
                } catch (Exception ex) {
                 JOptionPane.showMessageDialog(this, "Error "+ ex.getMessage()); ;
                } 
                break; // Sale del bucle               
            }
        }
    }
            JOptionPane.showMessageDialog(this, "Datos Guardados Con Éxito"); //Mensaje de que salio todo piola
      
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Test().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Test.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jt_EmpleadosAfter;
    private javax.swing.JTable jt_EmpleadosBefore;
    // End of variables declaration                   
}
